# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: sachacortez
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-image-app
region: ${file(config.json):AWS_REGION}

package:
  individually: true
  patterns:
    - '!config.json'
    - '!package.json'
    - '!package-lock.json'
    - '!serverless.yml'
    - '!README.md'
    - '!.gitignore'
provider:
  name: aws
  runtime: nodejs20.x
  environment:
    BUCKET_NAME: ${file(config.json):S3_BUCKET} 
    TABLE_NAME: ${file(config.json):DYNAMODB_TABLE}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:*
        - recognition:DetectLabels
      Resource:
        - arn:aws:s3:::${file(config.json):S3_BUCKET}/*

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

resources:
  Resources:
    UploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET_NAME}
    ImageTagsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: image
            AttributeType: S
        KeySchema:
          - AttributeName: image
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
          